// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4W4Yauvob4ket6qNBY8YEVyhNRhlTWSQ',
    appId: '1:937888834443:android:79cebefed59c8cc5dc058e',
    messagingSenderId: '937888834443',
    projectId: 'scaleupprojecttracker',
    databaseURL: 'https://scaleupprojecttracker-default-rtdb.firebaseio.com',
    storageBucket: 'scaleupprojecttracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHI1zU5e3lOgUt00mfft6GceKxoXWAPiY',
    appId: '1:937888834443:ios:3a2f176448a70a6cdc058e',
    messagingSenderId: '937888834443',
    projectId: 'scaleupprojecttracker',
    databaseURL: 'https://scaleupprojecttracker-default-rtdb.firebaseio.com',
    storageBucket: 'scaleupprojecttracker.appspot.com',
    androidClientId: '937888834443-iikj8j3a1ml7p4i2g6ru1mnd4dqsvpdg.apps.googleusercontent.com',
    iosClientId: '937888834443-4uj71umnnh5cq568l5rub29jgs73v7hc.apps.googleusercontent.com',
    iosBundleId: 'com.scaleup.cloudtracker',
  );
}
